"""Remove unique constraint from domain

Revision ID: 46b171e134ea
Revises: 
Create Date: 2024-12-28 12:39:56.967816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b171e134ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('imap_configurations_domain_key', 'imap_configurations', type_='unique')
    op.create_unique_constraint(None, 'imap_configurations', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imap_configurations', type_='unique')
    op.create_unique_constraint('imap_configurations_domain_key', 'imap_configurations', ['domain'])
    # ### end Alembic commands ###
