"""Add can_search_any to UserEmail

Revision ID: 69107973f643
Revises: 46b171e134ea
Create Date: 2024-12-28 13:24:24.379514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69107973f643'
down_revision = '46b171e134ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email', sa.Column('can_search_any', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_email', 'can_search_any')
    # ### end Alembic commands ###
